### ISSUE TITLE
templates not recognized

### ISSUE THREAD

**Issue by maciejskorski** [matter-labs/z-prize-msm-gpu-combined#3]
Compilation with Rust or directly by NVCC fails
`nvcc -ccbin=c++ -arch=sm_80 -c combined-msm/MSM.cu -o msm` 
With errors 
```bash
combined-msm/ml-ff-ec/memory.cuh(230): error: enable_if_t is not a template
```
My gut feel is this is because C++ standard used is not specified. That is, in addition to CUDA Toolkit version we have to know **the right version of C++ standard**. For instance, 

```bash
nvcc -ccbin=c++ -arch=sm_80 -c combined-msm/MSM.cu -o msm -std=c++17
```

**Comment by robik75** [comment]
Looking at the pull request, it looks like you are trying to compile it inside a container that is based on ubuntu 20.04, the problem seems to be that the toolchain coming with 20.04 is too old, if you switch to a container based on ubuntu 22.04 instead, it should work without the need to force the C++ standard.
That being said, this repository is representing a submission to z-prize 2022 and it should remain in the state it was submitted.
If you do not have any objections i will close this issue and the accompanying PR and archive this repo.

**Comment by robik75** [comment]
Since one week has passed and no objection was raised, i am closing this and #4 .
